[package]
name = "anaki_odbc"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.97"
odbc-api = "11.1.1"
rmp-serde = "1.1.2"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"